site_name: randomstuff.py
theme:
  name: material
  palette:
    - accent: green
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Toggle Light mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Toggle Dark mode

  icon:
    repo: fontawesome/brands/github


  font:
    text: Ubuntu
    code: Fira Code
  
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest
    - header.autohide

  language: en

nav:
  - Home:
    - Introduction: index.md
    - Getting Started: getting-started.md

  - Clients:
    - Client: sections/clients/client.md
    - AsyncClient: sections/clients/async-client.md

  - Data Classes:
    - Home: sections/data-classes/index.md
    - AIResponse: sections/data-classes/ai-response.md
    - Joke: sections/data-classes/joke.md
    - JokeFlags: sections/data-classes/joke-flags.md
    - Waifu: sections/data-classes/waifu.md
    - Weather: sections/data-classes/weather.md
    - WeatherLocation: sections/data-classes/weather-location.md
    - WeatherForecast: sections/data-classes/weather-forecast.md
    - CurrentWeather: sections/data-classes/current-weather.md

  - Errors:
    - Home: sections/errors/index.md
    - Forbidden: sections/errors/forbidden.md
    - BadAPIKey: sections/errors/bad-api-key.md
    - PlanNotAllowed: sections/errors/plan-not-allowed.md
    - ArgumentError: sections/errors/argument-error.md
    - UnknownArgument: sections/errors/unknown-argument.md
    - BadArgument: sections/errors/bad-argument.md
    - HTTPError: sections/errors/http-error.md

  - Submodules:
    - utils: sections/submodules/utils.md

  - Topics:
    - FAQ: sections/topics/faq.md
    - Warnings: sections/topics/warnings.md
    - Lists: sections/topics/lists.md
    - Unique ID: sections/topics/unique-id.md

  - What's new?:
    - What's new: sections/whats-new.md

extra:
  homepage: https://github.com/nerdguyahmad/randomstuff.py
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nerdguyahmad/randomstuff.py



copyright: Copyright &copy; 2021 - present NerdGuyAhmad
repo_url: https://github.com/nerdguyahmad/randomstuff.py
edit_uri: edit/main/docs/
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
